-- Comprehensive settings, SMTP/email, and secure password reset support.
CREATE TABLE IF NOT EXISTS system_settings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key varchar(120) NOT NULL UNIQUE,
    value text,
    is_secret boolean NOT NULL DEFAULT false,
    updated_by_id integer REFERENCES users(id),
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_system_settings_key ON system_settings(key);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL UNIQUE,
    expires_at timestamp NOT NULL,
    used_at timestamp,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_token_hash ON password_reset_tokens(token_hash);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

-- Seed safe non-secret defaults. Existing values are never overwritten.
INSERT INTO system_settings(key, value, is_secret)
VALUES
 ('site_name','Lead CRM',false),
 ('login_branding','Marketing Lead Management',false),
 ('theme','light',false),
 ('primary_color','#0d6efd',false),
 ('timezone','Asia/Kolkata',false),
 ('date_format','DD MMM YYYY',false),
 ('locale','en-IN',false),
 ('smtp_port','587',false),
 ('smtp_security','starttls',false),
 ('session_timeout_minutes','480',false),
 ('password_reset_expire_minutes','30',false),
 ('default_report_format','pdf',false)
ON CONFLICT (key) DO NOTHING;

ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version integer NOT NULL DEFAULT 0;
