CREATE TABLE IF NOT EXISTS product_categories (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL UNIQUE, description text, is_active boolean DEFAULT true, created_at timestamp DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(200) NOT NULL, sku varchar(100) UNIQUE, description text, category_id integer REFERENCES product_categories(id), price integer NOT NULL DEFAULT 0, currency varchar(10) NOT NULL DEFAULT 'INR', tax_percent integer NOT NULL DEFAULT 0, is_active boolean DEFAULT true, created_at timestamp DEFAULT CURRENT_TIMESTAMP, updated_at timestamp DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS ix_products_name ON products(name); CREATE INDEX IF NOT EXISTS ix_products_category_id ON products(category_id);
CREATE TABLE IF NOT EXISTS lead_products (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE, product_id integer NOT NULL REFERENCES products(id), quantity integer NOT NULL DEFAULT 1, interest_status varchar(30) NOT NULL DEFAULT 'interested', quoted_price integer, notes text, created_at timestamp DEFAULT CURRENT_TIMESTAMP, updated_at timestamp DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_lead_product UNIQUE(lead_id,product_id));
CREATE INDEX IF NOT EXISTS ix_lead_products_lead_id ON lead_products(lead_id); CREATE INDEX IF NOT EXISTS ix_lead_products_product_id ON lead_products(product_id);
CREATE TABLE IF NOT EXISTS conversions (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id integer NOT NULL UNIQUE REFERENCES leads(id) ON DELETE CASCADE, converted_by_id integer REFERENCES users(id), conversion_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, subtotal integer NOT NULL DEFAULT 0, discount integer NOT NULL DEFAULT 0, tax integer NOT NULL DEFAULT 0, total integer NOT NULL DEFAULT 0, notes text, created_at timestamp DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversion_items (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversion_id integer NOT NULL REFERENCES conversions(id) ON DELETE CASCADE, product_id integer REFERENCES products(id), product_name varchar(200) NOT NULL, sku varchar(100), quantity integer NOT NULL DEFAULT 1, unit_price integer NOT NULL DEFAULT 0, tax_percent integer NOT NULL DEFAULT 0, line_total integer NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS ix_conversion_items_conversion_id ON conversion_items(conversion_id);

INSERT INTO product_categories(name,description,is_active) VALUES
('Connectivity','Internet and connectivity services',true),
('Business Services','Business and enterprise services',true),
('Security','Security and surveillance services',true)
ON CONFLICT (name) DO NOTHING;
INSERT INTO products(name,sku,description,category_id,price,currency,tax_percent,is_active)
SELECT v.name,v.sku,v.description,c.id,v.price,'INR',v.tax,true FROM (VALUES
('Fiber 100 Mbps','FIBER100','100 Mbps Fiber Internet', 'Connectivity',799,18),
('Fiber 200 Mbps','FIBER200','200 Mbps Fiber Internet', 'Connectivity',999,18),
('Fiber 500 Mbps','FIBER500','500 Mbps Fiber Internet', 'Connectivity',1499,18),
('Fiber 1 Gbps','FIBER1G','1 Gbps Fiber Internet', 'Connectivity',2499,18),
('Static IP','STATICIP','Dedicated static IPv4 address', 'Business Services',500,18),
('Business Fiber','BIZFIBER','Business-grade Fiber Internet', 'Business Services',2999,18),
('Managed WiFi','MWIFI','Managed WiFi service', 'Business Services',299,18),
('CCTV Package','CCTVPKG','Multi-camera CCTV package', 'Security',8999,18),
('Cloud Backup','CLOUDBAK','Managed cloud backup service', 'Business Services',1299,18),
('Enterprise Connectivity','ENTCONN','Enterprise connectivity service', 'Business Services',5999,18)
) AS v(name,sku,description,category,price,tax) JOIN product_categories c ON c.name=v.category
ON CONFLICT (sku) DO NOTHING;

-- Attach a few catalogue products to the existing demo leads when present.
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, 'interested', p.price
FROM leads l JOIN products p ON p.sku IN ('FIBER100','STATICIP')
WHERE l.email = 'demo.lead01@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, CASE WHEN l.status::text='converted' THEN 'won' ELSE 'quoted' END, p.price
FROM leads l JOIN products p ON p.sku IN ('FIBER200','MWIFI')
WHERE l.email = 'demo.lead02@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, 'negotiating', p.price
FROM leads l JOIN products p ON p.sku IN ('FIBER500')
WHERE l.email = 'demo.lead03@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, 'interested', p.price
FROM leads l JOIN products p ON p.sku IN ('BIZFIBER','CLOUDBAK')
WHERE l.email = 'demo.lead04@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, 'quoted', p.price
FROM leads l JOIN products p ON p.sku IN ('CCTVPKG')
WHERE l.email = 'demo.lead05@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
INSERT INTO lead_products(lead_id, product_id, quantity, interest_status, quoted_price)
SELECT l.id, p.id, 1, 'won', p.price
FROM leads l JOIN products p ON p.sku IN ('FIBER1G','STATICIP')
WHERE l.email = 'demo.lead06@example.com'
ON CONFLICT (lead_id, product_id) DO NOTHING;
